### ISSUE TITLE
Locale issue

### ISSUE THREAD

**Issue by mikkeschiren** [marketsystems/nextjs13-appdir-breadcrumbs#1]
Hi! 

First of all, great work on this component!

I have tried it out and it worked really well, but I have one issue.
For the site I am building, we have many different locales (en, de, sv etc.).
The locale is part of the URL, like: example.org/de/about.

My root layout is inside a [lang] folder - because I want to use the locale as   `<html lang={params.lang}>`.

With the component, I can never remove the locale from the index, it will always be like:
Home > de > My path

It would be nice if it should be possible to use this component together with different locales.

**Comment by ejkkan** [comment]
Also running into this!

**Comment by marketsystems** [comment]
I didnt write the original component, but couldnt you do something with this:

Omit certain path indexes from breadcrumb navigation
It's possible to pass an array containing all the indexes of the path that should be omitted and not be rendered as labels. If we have a path like /home/category/1 then you might want to pass [2] here, which omits the breadcrumb label 1. Indexes start with 0. Example: [2] Default: undefined.

import React from "react";
import Breadcrumbs from "@marketsystems/nextjs13-appdir-breadcrumbs";

// path: /nested/this-is-ommited will omit the this-is-ommited breadcrumb
const Example = () => {
  return <Breadcrumbs useDefaultStyle={true} omitIndexList={[1]} />;
};
