### ISSUE TITLE
listClassName doesn't apply

### ISSUE THREAD

**Issue by Karina1703** [marketsystems/nextjs13-appdir-breadcrumbs#2]
I love your library, but I found some bug. I use next@13.4.3

			<Breadcrumbs
				useDefaultStyle
				rootLabel="Home"
				listClassName = "hello" // doesn't apply
				activeItemClassName = "text-cyan-500"
			/>
			
			
			
package.json
	"dependencies": {
		"@editorjs/editorjs": "^2.27.2",
		"@editorjs/header": "^2.7.0",
		"@headlessui/react": "^1.7.14",
		"@hookform/resolvers": "^3.1.0",
		"@marketsystems/nextjs13-appdir-breadcrumbs": "^1.0.4",
		"@sentry/nextjs": "^7.53.0",
		"@tailwindcss/aspect-ratio": "^0.4.2",
		"@tailwindcss/forms": "^0.5.3",
		"@tailwindcss/typography": "^0.5.9",
		"@types/node": "20.2.3",
		"@types/react": "18.2.6",
		"@types/react-dom": "18.2.4",
		"@use-platform/react": "^1.0.0-rc.dc945ca.7",
		"ag-grid-community": "^30.0.2",
		"ag-grid-enterprise": "^30.0.2",
		"ag-grid-react": "^30.0.2",
		"axios": "^1.4.0",
		"class-variance-authority": "^0.6.0",
		"classnames": "^2.3.2",
		"eslint": "8.41.0",
		"eslint-config-next": "13.4.3",
		"focus-visible": "^5.2.0",
		"mobx": "^6.9.0",
		"mobx-react-lite": "^3.4.3",
		"next": "13.4.3",
		"next-auth": "^4.22.1",
		"next-intl": "^3.0.0-beta.9",
		"postcss": "8.4.23",
		"react": "18.2.0",
		"react-dom": "18.2.0",
		"react-hook-form": "^7.44.2",
		"react-select": "^5.7.3",
		"sass": "^1.62.1",
		"tailwindcss": "3.3.2",
		"tslib": "^2.5.2",
		"typescript": "5.0.4",
		"yup": "^1.2.0"
	},
	"devDependencies": {
		"@storybook/addon-essentials": "^7.0.15",
		"@storybook/addon-interactions": "^7.0.15",
		"@storybook/addon-links": "^7.0.15",
		"@storybook/blocks": "^7.0.15",
		"@storybook/nextjs": "^7.0.15",
		"@storybook/react": "^7.0.15",
		"@storybook/testing-library": "^0.0.14-next.2",
		"@svgr/webpack": "^8.0.1",
		"@trivago/prettier-plugin-sort-imports": "^4.1.1",
		"@types/editorjs__header": "^2.6.0",
		"autoprefixer": "^10.4.14",
		"chromatic": "^6.18.0",
		"eslint-plugin-storybook": "^0.6.12",
		"local-ssl-proxy": "^2.0.5",
		"prettier": "^2.8.8",
		"react-use": "^17.4.0",
		"storybook": "^7.0.15",
		"tsconfig-paths-webpack-plugin": "^4.0.1"
	}
}

**Comment by marketsystems** [comment]
I did not write the original component, only modified it. But it does work with listClassName as I have used it in my own project, you have to make sure that useDefaultStyle is set to false for it to apply
